const JOB_TYPE = {
    DESKTOP: 1,
    REAL_DEVICE: 2,
    VIRTUAL_DEVICE: 4,
    LIVE: 8,
    AUTOMATED: 16,
    WEB: 32,
    APP: 64
}

/* Need:
- [x] RDC web test
- [x] RDC app test
- [ ] RDC espresso/xcui test
- [ ] desktop VDC test
- [ ] emusim VDC test
- [ ] LIVE for all the above?
*/

const AUTOMATED_RDC = (JOB_TYPE.APP & JOB_TYPE.REAL_DEVICE & JOB_TYPE.AUTOMATED)
const AUTOMATED_DESKTOP = (JOB_TYPE.DESKTOP & JOB_TYPE.AUTOMATED)
const RDC_WEB  = (JOB_TYPE.WEB & JOB_TYPE.REAL_DEVICE)
const LIVE_DESKTOP = (JOB_TYPE.DESKTOP & JOB_TYPE.LIVE)
const EMUSIM_WEB = (JOB_TYPE.VIRTUAL_DEVICE | JOB_TYPE.WEB)
const EMUSIM_APP = (JOB_TYPE.VIRTUAL_DEVICE & JOB_TYPE.APP)

export { JOB_TYPE,  AUTOMATED_RDC, AUTOMATED_DESKTOP, RDC_WEB, LIVE_DESKTOP, EMUSIM_APP, EMUSIM_WEB}